//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dsdad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dsdad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /chr/c0000.anibnd.dcx
        /// /chr/c0000.chrbnd.dcx
        /// /chr/c0000.esd.dcx
        /// /chr/c0000_a00_hi.anibnd.dcx
        /// /chr/c0000_a00_lo.anibnd.dcx
        /// /chr/c0000_a00_md.anibnd.dcx
        /// /chr/c0000_a0x.anibnd.dcx
        /// /chr/c0000_a1x.anibnd.dcx
        /// /chr/c0000_a2x.anibnd.dcx
        /// /chr/c0000_a3x.anibnd.dcx
        /// /chr/c0000_a4x.anibnd.dcx
        /// /chr/c0000_a5x.anibnd.dcx
        /// /chr/c0000_a6x.anibnd.dcx
        /// /chr/c0000_a7x.anibnd.dcx
        /// /chr/c0000_a8x.anibnd.dcx
        /// /chr/c0000_a9x.anibnd.dcx
        /// /chr/c0000_c2060.anibnd.dcx
        /// /chr/c0000_c2290.anibnd.dcx
        /// /chr/c0000_c2300.anibnd.dcx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string filenames {
            get {
                return ResourceManager.GetString("filenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mask_of_the_father {
            get {
                object obj = ResourceManager.GetObject("mask_of_the_father", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
